name: Virtual PC

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Install Tailscale
        run: |
          choco install tailscale -y

      - name: Login Tailscale
        run: |
          & "C:\Program Files\Tailscale\tailscale.exe" up --authkey tskey-auth-kJZ5qkfG4J11CNTRL-G8LPrmaFuBMskHGYx4B4CM7pwRKHinjf

      - name: Enable RDP
        run: |
          Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Terminal Server" -Name "fDenyTSConnections" -Value 0
          net user runneradmin 123456

      - name: Keep Alive
        run: |
          ping localhost -t
